config/routes.rb
Rails.application.routes.draw do
  get "/classroom-utilization", to: "classroom_utilization#index"
  get "/days/:date", to: 'events#show_date', as: "show_date"
  get "/weeks/:year/:number", to: 'events#show_week'
  root to: 'events#show_date'
  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :spaces do
    resources :events
  end
  resources :event_types
  resources :recurring_events
  get '/utilizations', to: "utilizations#index"
  resources :recurring_events, only: [:create, :update, :destroy]
  get 'events/check_availability', to: 'events#check_availability'
  get 'events/queue', to: 'events#queue'
  resources :events do
    patch :update_approval
    resources :notes
  end
  get 'settings', to: 'settings#index'
  get 'front-lines', to: 'static#front_lines'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :reservations
  has_many :notes, dependent: :destroy
  belongs_to :space
  belongs_to :event_type
  belongs_to :recurring_event

  # validate :is_available, :is_postive_time, :room_capactity
  validates :space_id, :start_date, :end_date, :title, :event_style, presence: true

  scope :unapproved, -> { where(approved: [nil, false]) }
  scope :same_space, -> (space_id){ where('space_id = ?', space_id)}
  scope :diff_event, -> (event_id){ where('id != ?', event_id)}
  scope :overlaping, -> (start, endd){
    return [] if endd - start > 1.day
    where('(? < end_date AND ? > start_date)', start, endd)
  }
  scope :by_date, -> (day){ where(start_date: day.beginning_of_day..day.end_of_day)}

  include IceCube
  attr_accessor :recurring_rules

  def repeat days
    days = self.end_date - self.start_date
    current_day = self.start_date
    days.each do |d|
      current_day += 1
    end
  end
  def as_json(options = { })
      h = super(options)
      h[:color]   =  self.event_type && self.event_type.color || "#000"
      h
  end
  def is_available
    start = self.start_date
    endd = self.end_date
    if self.id
      @events = Event.same_space(self.space_id).diff_event(self.id).overlaping(start, endd)
    else
      @events = Event.same_space(self.space_id).overlaping(start, endd)
    end
    if @events.count > 0
      errors.add(:event, "space and time are not available during the date/time you requested.<br>These events conflict: " + @events.map{|e|  "https://gadc.space/events/" + e.id.to_s }.join("<br>"))
    end
  end
  def is_postive_time
    if (self.start_date > self.end_date) || (self.start_date == self.end_date)
      errors.add(:event, "time is not valid, the start must come before the end.")
    end
  end
  def room_capactity
    @space = Space.find(self.space_id)
    cap = @space.classroom_cap || @space.lecture_cap
    if self.event_style == 'Lecture'
      if cap && self.number_of_attendees && self.number_of_attendees > cap
        errors.add(:event, "space selected has a max lecture capacity of #{@space.lecture_cap}, please select a different space." )
      end
    else
      if cap && self.number_of_attendees && self.number_of_attendees > cap
        errors.add(:event, "space selected has a max classroom capacity of #{@space.classroom_cap}, please select a different space." )
      end
    end
  end
  # TODO validation for recurring events sucks
  # TODO can't update non-recurring event to become recurring
  def color
    if self.custom_color
      self.custom_color
    elsif self.event_type
      self.event_type.color
    end
  end
  def self.recurring_helper(params, event_params, start_date, end_date)
    rec_rules  = RecurringSelect.dirty_hash_to_rule(params['event']['recurring_rules'])
    dur_in_sec = end_date.seconds_since_midnight - start_date.seconds_since_midnight
    total_dur = (end_date.strftime("%s").to_i - start_date.strftime("%s").to_i)
    sched = Schedule.new(start_date, :duration => total_dur)
    sched.add_recurrence_rule(rec_rules)
    occurrences = sched.occurrences_between(start_date, end_date + 1.day)
    occurrences = occurrences.map{|o| o.to_datetime.change(:offset => "+0000")}
    return [dur_in_sec, sched, occurrences]
  end
  def self.update_recurring_events(params, event_params, start_date, end_date, recurring_event)
    new_st = start_date
    new_et = end_date
    if start_date.strftime('%D') == end_date.strftime('%D')
      old_st = recurring_event.start_date.to_datetime
      old_et = recurring_event.end_date.to_datetime
      start_date = DateTime.new(old_st.year, old_st.month, old_st.day, new_st.hour, new_st.minute, new_st.second)
      end_date = DateTime.new(old_et.year, old_et.month, old_et.day, new_et.hour, new_et.minute, new_et.second)
    end
    dur_in_sec, sched, occurrences = self.recurring_helper(params, event_params, start_date, end_date)
    recurring_event.update!(event_params.merge(start_date: start_date, end_date: end_date, recurring_rules: sched.to_hash))
    occurrences.each do |occurrence|
      recurring_event.events.create!(event_params.merge(start_date: occurrence, end_date: occurrence + dur_in_sec.seconds))
    end
  end
  def self.create_recurring_events(params, event_params, start_date, end_date)
    dur_in_sec, sched, occurrences = self.recurring_helper(params, event_params, start_date, end_date)
    rec = RecurringEvent.create!(event_params.merge(start_date: start_date, end_date: end_date, recurring_rules: sched.to_hash))
  end
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  has_many :events
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include IceCube
  def show
    @event = Event.find(params[:id])
    if @event.recurring_event_id
      @recurring_event = RecurringEvent.find(@event.recurring_event_id)
    end
    @note = Note.new
  end
  def queue
    authorize! :approve, @event
    @events = Event.unapproved.order(start_date: :desc)
  end
  def new
    @event = Event.new
    @day = params[:day]
  end
  def create
    start_date = DateTime.parse(params[:event][:start_date])
    end_date = DateTime.parse(params[:event][:end_date])
    if params[:event][:recurring_rules] != "null"
      Event.create_recurring_events(params, event_params, start_date, end_date)
      redirect_to root_path
    else
      @event = Event.new(event_params.merge(start_date: start_date, end_date: end_date))
      if @event.save
	       @event.notes.create(text: params[:notes]) unless params[:notes].empty?
        respond_to do |format|
          format.html { redirect_to show_date_path(@event.start_date.strftime("%F")) }
          format.json { render json: @event }
        end
      else
        render "new"
      end
    end
  end
  def edit
    @event = Event.find(params[:id])
    if @event.recurring_event_id
      @recurring_event = RecurringEvent.find(@event.recurring_event_id)
    else
    end
    @recurring_event = nil
  end

  def update
    start_date = DateTime.parse(params[:event][:start_date])
    end_date = DateTime.parse(params[:event][:end_date])
    @event = Event.find(params[:id])
    recurring_event = @event.recurring_event if @event.recurring_event_id
    @recurring_event = recurring_event
    if params[:update_all]
      begin
        Event.update_recurring_events(params, event_params, start_date, end_date, recurring_event)
      rescue Exception => e
        @recurring_event.errors.add(:start_date, e.to_s)
        return render :edit
      end
      go_back
    else
      if @event.update(event_params.merge(start_date: start_date, end_date: end_date))
      	respond_to do |format|
      	  format.html { redirect_to show_date_path(@event.start_date.strftime("%F")) }
      	  format.json { render json: @event }
      	end
      else
      	render "edit"
      end
    end
  end
  def update_approval
    # TODO bulk approval for recurring_events
    @event = Event.find(params[:event_id])
    if params[:commit] == 'Approve'
      @event.approved = true
    end
    if @event.save
      redirect_to events_queue_path
    else
      flash[:notice] = @event.errors.full_messages.join("")
      redirect_to events_queue_path
    end
  end
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    go_back
  end
  def show_date
    return search unless params[:query].blank?
    day = params[:date] || Date.today.to_s
    @day = Date.parse(day)
    @dayparams = @day.strftime("%F")
    session[:back] = show_date_path(@day, params[:view])
    @today = @day.strftime("%A, %b %e, %Y")
    @yesterday = (Date.parse(day) - 1.day).strftime("%F")
    @tomorrow = (Date.parse(day) + 1.day).strftime("%F")
    @spaces = Space.all
    @events = Event.by_date(@day).order('start_date ASC')
    @year = Date.parse(day).strftime("%Y")
    @week = Date.parse(day).strftime("%W")
    if params[:view] == "week"
      @events = Event.where("start_date > ? AND end_date < ?", @day.beginning_of_week, @day.end_of_week)
    end
    if params[:view] == "month"
      @day = Date.parse(params[:start_date]) if params[:start_date]
      @events = Event.where("start_date > ? AND end_date < ?", @day.beginning_of_month, @day.end_of_month)
    end
    session[:last_view] = request.original_url
  end
  def check_availability
    start = DateTime.parse(params[:start_date])
    endd = DateTime.parse(params[:end_date])
    @events = Event.same_space(params[:space_id]).overlaping(start, endd)
    if @events.count > 0
      render json: false
    else
      render json: true
    end
  end
  private
  def search
    @events = Event.where("lower(title) LIKE ?", "%" + params[:query].downcase + "%" )
    render :search
  end

  def event_params
    params.require(:event).permit(:title, :space_id, :event_type_id, :producer, :approved, :instructor, :number_of_attendees, :start_date, :end_date, :kind, :event_style, :recurring_rules, :custom_color)
  end

  def go_back
    return redirect_to session[:last_view] if session[:last_view]
    redirect_to :back
  end
end

app/views/events/_agenda.html.erb
<h2>&nbsp;<%= @today %>&nbsp;</h2>
<%= link_to "&laquo; Yesterday".html_safe, show_date_path(@yesterday, request.query_parameters), class: 'button' %>
<%= link_to "Tomorrow &raquo;".html_safe, show_date_path(@tomorrow, request.query_parameters), class: 'button' %>
<div class='wrap agenda'>
 <% @events.each do |event| %> 
   <div class='event' data-color="<%= event.color %>">
     <a class='left' href='<%= event_path(event) %>' style='background: <%= event.color %>'>
       <span><%= event.title %><span>
     </a>
     <div class='right'><%= event.space.title %>
     </div>
     <ul>
       <li><strong>Time:</strong> <%= event.start_date.strftime("%l:%M%p") %> - <%= event.end_date.strftime("%l:%M%p") %>
       </li>
       <li><strong>Room:</strong> <%= event.space.title %></li>
       <% if event.producer %>
	 <li><strong>Producer:</strong> <%= event.producer%></li>
       <% end %>
       <% unless event.instructor.blank? %>
	 <li><strong>Instructor:</strong> <%= event.instructor%></li>
       <% end %>
       <% unless event.notes.empty? %>
	 <li><strong>Notes:</strong>
	   <ul>
	     <% event.notes.each do |note| %>
	       <li><%= note.text %></li>
	     <% end %>
	   </ul>
	 </li>
       <% end %>
     </ul>
   </div>
 <% end %>
</div>

app/views/events/_d3repeated.html.erb
<script>
  // y axis
  svg
  .append("g")
  .attr("class","Y Axis")
  .selectAll("text")
  .data(spaces)
  .enter()
  .append("text")
  .attr("dx", "-60")
  .attr("dy","-1em")
  .attr("fill", "#000")
  .style("font-size", "10px")
  .attr("y", function(d, i){
    return (i * rowHeight) + 30;
  })
  .text(function(d){
    return d.title
  })
  .call(wrap, 60)
  .selectAll(".Y tspan")
  .attr("dx", "-7em")

  // y lines
  svg.append("g")
  .selectAll("line")
  .data(spaces)
  .enter()
  .append("line")
  .attr("x1", 0)
  .attr("y1", function(d, i){
    return (i * rowHeight);
  })
  .attr("x2", "100%")
  .attr("y2", function(d, i){
    return (i * rowHeight);
  })
  .attr("stroke", "#eee")
  .attr("stroke-width", "1")

  var tooltip = d3
  .select("body")
	.append("div")
  .attr('class', 'd3-tip')

  var square = d3
  .select(".cal")
  .selectAll(".events")
  .data(data)
  .enter()
  .append("g")
  .attr("class","events")
  .on("mouseover", function(d){
    tooltip
    .html(function(){
      var el = "<p>"+ d.title +"</p>"
      +"<p>"+ moment.utc(d.start_date).format("h:mma") + " - " + moment.utc(d.end_date).format("h:mma") +"</p>"
      +"<p>Producer: "+ d.producer +"</p>"
      +"<p>Instructor: "+ d.instructor +"</p>"
      +"<p>Attendees: "+ d.number_of_attendees +"</p>"
      d.notes.forEach(function(n){ el += "<li>"+ n.text +"</li>"})
      return el
    })
    .style("visibility", "visible")
    .style("position", "absolute");
    return tooltip;
  })
  .on("mousemove", function(){
    return tooltip.style("top", (d3.event.pageY-10)+"px").style("left",(d3.event.pageX+10)+"px");
  })
  .on("mouseout", function(){
    return tooltip.style("visibility", "hidden");
  });

  square.append("rect")
  .text(function(d){
    return d.id
  })
  .attr("y", function(d, i){
    var spaceIds = spaces.map(function(d){
      return d.id
    })
    return spaceIds.indexOf(d.space_id) * rowHeight
  })
  .attr("width", squareWidth)
  .attr("height", rowHeight)
  .style("fill", function(d){
    return d.custom_color ? d.custom_color : d.color;
  })
  .attr("x", offsetX)
  .attr("data-approved", function(d){
    return d.approved ? "" + d.approved : "false"
  })
  .attr("href", function(d){
    return "/events/" + d.id
  })

  square
  .on("click", function( ){
    var href = this.querySelector("rect").getAttribute("href");
    window.location = href
  })

  square
  .append("foreignObject")
  .attr("x", offsetX)
  .attr("y", function(d, i){
    var spaceIds = spaces.map(function(d){
      return d.id
    })
    return spaceIds.indexOf(d.space_id) * rowHeight
  })
  .attr("width",squareWidth)
  .attr("height","100%")
  .attr("dy", "1.25em")
  .attr("dx", ".25em")
  .attr("fill", "#fff")
  .style("font-size", "10px")
  .style("overflow", "hidden")
  .style("font-weight", "bold")
  .text(function(d){
    return d.title
  })

  function wrap(text, width) {
    text.each(function() {
      var text = d3.select(this),
          words = text.text().split(/\s+/).reverse(),
          word,
          line = [],
          lineNumber = 0,
          lineHeight = 1.1, // ems
          y = text.attr("y"),
          dy = parseFloat(text.attr("dy")),
          tspan = text.text(null).append("tspan").attr("x", 0).attr("y", y).attr("dy", dy + "em");
      while (word = words.pop()) {
        line.push(word);
        tspan.text(line.join(" "));
        if (tspan.node().getComputedTextLength() > width) {
          line.pop();
          tspan.text(line.join(" "));
          line = [word];
          tspan = text.append("tspan").attr("x", 0).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word);
        }
      }
    });
  }
</script>

app/views/events/_day.html.erb
<h2>&nbsp;<%= @today %>&nbsp;</h2>
<%= link_to "&laquo; Yesterday".html_safe, show_date_path(@yesterday, request.query_parameters), class: 'button' %>
<%= link_to "Tomorrow &raquo;".html_safe, show_date_path(@tomorrow, request.query_parameters), class: 'button' %>
<br>

<div class='wrap'>
  <svg class='cal'></svg>
</div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.16/d3.js'></script>
<script>
  var spaces = <%= @spaces.to_json.html_safe %>;
  var data = <%= @events.to_json(include: :notes).html_safe %>;
  var scaleX = d3.scale.linear().domain([8,22]).range([0,100])
  var rowHeight = 40;
  function offsetX(d){
     var m = moment.utc(d.start_date)
     var hours = parseInt(m.format("H"))
     var minutes = m.format("m") / rowHeight;
     return scaleX(hours + minutes) +"%"
  }
  function squareWidth(d){
    var now  = d.start_date;
    var then = d.end_date;
    var ms = moment(then).diff(moment(now));
    var du = moment.duration(ms);
    var hs = du.asHours()
    return scaleX(hs + 8) +"%"
  }

  var svg = d3
  .select(".cal")

  // x axis
  svg
  .append("g")
  .attr("class","X Axis")
  .selectAll("text")
  .data([8,9,10,11,12,13,14,15,16,17,18,19,20,21,22])
  .enter()
  .append("text")
  .attr("x",function(d){
    return scaleX(d) + "%"
  })
  .attr("dy","-1em")
  .attr("fill", "#000")
  .style("font-size", "10px")
  .text(function(d){
    return d
  })
</script>
<%= render "d3repeated" %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <% @event.errors.full_messages.each do |err| %>
    <div class='error'>
      <%= err.html_safe %>
    </div>
  <% end %>
<% end %>
<% if @recurring_event && @recurring_event.errors.any? %>
  <% @recurring_event.errors.full_messages.each do |err| %>
    <div class='error'>
      <%= err.html_safe %>
    </div>
  <% end %>
<% end %>
<%= form_for @event do |f| %>
  <span id='event' data='<%= @event.id %>' style='display: none'>Event</span>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <br>
  <%= f.label :space_id %>
  <%= f.select :space_id, Space.all.collect{|s| [s.title, s.id] } %>
  <br>
  <%= f.label :custom_color %>
  <input class='js-custom-color' type='color' name='event[custom_color]' value='<%= @event.color %>'>
  <script> var colors = <%= Hash[EventType.all.map{|et| [et.title, et.color] }].to_json.html_safe %></script>
  <span class="swatch start">S</span>
  <span class="swatch middle">M</span>
  <span class="swatch end">E</span>
  <br>
  <%= f.label :event_style %>
  <%= f.select :event_style, ["Class", "Lecture", "Other - See Notes"], selected: "Class" %>
  <br>
  <%= f.label :event_type_id %>
  <% kinds = ["Immersive", "Part Time Course", "Info Session", "C&W", "Event", "Alumni", "Internal"]%>
  <%= f.select :event_type_id, EventType.all.collect{|et| [et.title, et.id] } %>
  <br>
  <% if @recurring_event %>
    <span id='recurring_event' data='<%= @recurring_event.id %>' style='display: none'>Recurring Event</span>
    <%= f.label :start_date %>
    <input class='datetimepicker' name='event[start_date]' required="true" value="<%= @recurring_event.start_date%>" >
    <br>
    <%= f.label :end_date %>
    <input class='datetimepicker' name='event[end_date]' required="true" value="<%=@recurring_event.end_date %>">
    <br>
    <%= f.label :recurring_rules, "Recurring?" %>
    <%= f.select_recurring :recurring_rules, [
      IceCube::Schedule.from_hash(@recurring_event.recurring_rules).recurrence_rules[0],
      IceCube::Rule.daily,
      IceCube::Rule.weekly.day(:monday, :tuesday, :wednesday, :thursday, :friday)
      ] %>
  <% else %>
    <%= f.label :start_date %>
    <input class='datetimepicker' name='event[start_date]' required="true" value="<%= @event.start_date%>" >
    <br>
    <%= f.label :end_date %>
    <input class='datetimepicker' name='event[end_date]' required="true" value="<%=@event.end_date %>">
    <br>
    <%= f.label :recurring_rules, "Recurring?" %>
    <%= f.select_recurring :recurring_rules, [
    IceCube::Rule.weekly.day(:monday, :wednesday),
    IceCube::Rule.weekly.day(:tuesday, :thursday),
    IceCube::Rule.weekly.day(:monday, :tuesday, :wednesday, :thursday, :friday)
    ], :allow_blank => true %>
  <% end %>
  <br>
  <%= f.label :producer %>
  <%= f.text_field :producer, required: true %>
  <br>
  <%= f.label :instructor %>
  <%= f.text_field :instructor %>
  <br>
  <%= f.label :number_of_attendees %>
  <%= f.number_field :number_of_attendees %>
  <br>
  <% if can? :approve, @event %>
  <%= f.label :approved %>
  <%= f.check_box :approved %>
  <br>
  <% end %>
  <% if @recurring_event %>
  <%= f.submit :"Update all", name: 'update_all', data: {confirm: "Are you sure? This will change all events in the series."} %>
  <% else %>
  <%= f.submit %>
  <% end %>

  <% if !@event.id %>
    <h3>Notes</h3>
    <%= text_area_tag :notes, "", required: true %>
    <br>
  <% end %>
<% end %>

app/views/events/_month.html.erb
<%= month_calendar(attribute: :start_date, events: @events) do |date, events| %>
  <strong><small><%= link_to date.strftime("%m/%d"), show_date_path(date.to_s)  %></small></strong>
  <% events.each do |event| %>
    <div>
      <%= link_to event.title, event_path(event) %>
    </div>
  <% end %>
<% end %>

app/views/events/_week.html.erb
<%= link_to "&laquo; Prev Week".html_safe, show_date_path((@day - 1.week).strftime("%F"),request.query_parameters), class: 'button' %>
<%= link_to "Next Week &raquo;".html_safe, show_date_path((@day + 1.week).strftime("%F"),request.query_parameters), class: 'button' %>
<br>

<div class='wrap'>
  <svg class='cal'></svg>
</div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.16/d3.js'></script>
<script>
  var spaces = <%= @spaces.to_json.html_safe %>;
  var data = <%= @events.to_json(include: :notes).html_safe %>;
  var scaleX = d3.scale.linear().domain([8,22]).range([0,100])
  var rowHeight = 40;
  function offsetDayX(d){
     var m = moment.utc(d.start_date)
     var dayOfWeek = m.day();
     var hours = parseInt(m.format("H"))
     var minutes = m.format("m") / rowHeight;
     return scaleX(hours + minutes) * (1/7)
  }
  function offsetX(d){
     var m = moment.utc(d.start_date)
     var dayOfWeek = m.day() - 1;
     return scaleWeek(dayOfWeek) + offsetDayX(d) + "%"
  }
  function squareWidth(d){
    var now  = d.start_date;
    var then = d.end_date;
    var ms = moment(then).diff(moment(now));
    var du = moment.duration(ms);
    var hs = du.asHours()
    return ((scaleX(hs + 8)) / 7) +"%"
  }

  var scaleWeek = d3.scale.linear().domain([0,7]).range([0,100])
  // create array of momment objects of dates from empty array
  var dates = new Array(7).fill('').map(function(el, i){
    var m = moment('<%= @day.beginning_of_week%>')
    var d = m.add(i, 'days')
    return d;
  })

  var svg = d3
  .select(".cal")

  // x axis
  var xAxis = svg
  .append("g")
  .attr("class","X Axis week")
  .selectAll("text")
  .data(dates)
  .enter()
  .append("g")

  xAxis
  .append("rect")
  .attr("x",function(d, i){
    return scaleWeek(i) + "%"
  })
  .attr("rx","3")
  .attr("ry","3")
  .attr("stroke", "#ccc")
  .attr("y", "-2.25em")
  .attr("width", "5em")
  .attr("height", "1.75em")
  .attr("dy","-1em")
  .attr("fill", "#fff")
  .style("font-size", "10px")
  .text(function(d){
    return d.format('dd MM/DD')
  })
  .on("click", function(d){
    var href = "/days/"+ d.format('YYYY-MM-DD')
    window.location = href
  })

  xAxis
  .append("text")
  .attr("x",function(d, i){
    return scaleWeek(i)+.5 + "%"
  })
  .attr("dy","-1em")
  .attr("fill", "#000")
  .style("font-size", "10px")
  .text(function(d){
    return d.format('dd MM/DD')
  })
  .on("click", function(d){
    var href = "/days/"+ d.format('YYYY-MM-DD')
    window.location = href
  })

</script>
<%= render "d3repeated" %>

app/views/events/edit.html.erb
<%= render "events/form",  locals: {recurring_event: @recurring_event} %>

app/views/events/index.html.erb
<%= link_to "New Event", new_event_path %>
<% @events.each do |e| %>
  <%= e.inspect %>
<% end %>

app/views/events/queue.html.erb
<p><%= @events.count %> events to process</p>
<% @events.each do |e| %>
  <% if e.errors.any? %>
    <% e.errors.full_messages.each do |err| %>
      <div class='error'>
        <%= err %>
      </div>
    <% end %>
  <% end %>
  <div class="queue_item">
    <h2><%= e.title %></h2>
    <p><%= e.start_date.strftime("%F %H:%M") %> - <%= e.end_date.strftime("%F %H:%M") %></p>
    <p><%= e.kind %></p>
    <p><%= Space.find(e.space_id).title %></p>
    <p><%= e.producer %></p>
    <p><%= e.instructor %></p>
    <%= form_for e, url: event_update_approval_path(e), method: :patch do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :start_date %>
      <%= f.hidden_field :end_date %>
      <%= f.hidden_field :space_id %>
      <%= f.hidden_field :kind %>
      <%= f.hidden_field :producer %>
      <%= f.hidden_field :instructor %>
      <%= f.hidden_field :event_type_id %>
      <%= f.hidden_field :number_of_attendees %>
      <%= f.hidden_field :approved %>
      <%= f.submit 'Approve', class: 'button' %>
    <% end %>
    <%= link_to 'Edit', edit_event_path(e), class: 'button'%>
    <%= link_to 'Details', event_path(e), class: 'button' %>
  </div>
<% end %>

app/views/events/search.html.erb
<% if @events.any? %>
  <h3>Results</h3>
  <ul>
  <% @events.each do |event| %>
    <li><%= link_to "#{event.title} - #{event.start_date.strftime("%F")}", event %>
    </li>
  <% end %>
  </ul>
  <% else %>
  <p>No Results Found</p>
<% end %>

app/views/events/show.html.erb
<%= link_to "&laquo; Back".html_safe, session[:back] if session[:back] %>
<h2><%= @event.title %></h2>
<% if @recurring_event %>
  <% if can? :approve, @event %>
    <%= link_to "Edit All", edit_recurring_event_path(@recurring_event), class: 'button' %>
    <%= link_to "Delete All", recurring_event_path(@recurring_event), method: :delete, data: {confirm: "Are you sure?"}, class: 'button' %>
  <% end %>
<% end %>
<p><%= @event.start_date.strftime("%F %H:%M") %> -
  <%= @event.end_date.strftime("%F %H:%M") %></p>
<p><%= @event.space.title %></p>
<p>Type: <%= @event.event_type.title %></p>
<p>Event Style: <%= @event.event_style %></p>
<p>Attendees: <%= @event.number_of_attendees %></p>
<p>Producer: <%= @event.producer %></p>
<p>Instructor: <%= @event.instructor %></p>
<% if can? :approve, @event %>
  <%= link_to "Edit", edit_event_path(@event), class: 'button'%>
  <%= link_to "Delete", event_path(@event), method: :delete, data: {confirm: "Are you sure?"}, class: 'button' %>
<% end %>
<h3>Notes</h3>
<%= form_for [@event, @note] do |f| %>
  <%= f.text_area :text %>
  <%= f.submit %>
<% end %>
<% @event.notes.each do |note| %>
  <div class='note'>
    <p>
      <%= note.text %>
    </p>
    <small>Last updated <%= time_ago_in_words(note.updated_at) %> ago</small>
    <% if note.user %>
      <small>by <%= note.user.name%></small>
    <% end %>
    <% if note.user == current_user %>
      <%= link_to "Edit", edit_event_note_path(@event, note), class: 'button'%>
      <%= link_to "Delete", event_note_path(@event, note), method: :delete, data: {confirm: "Are you sure?"}, class: 'button' %>
    <% end %>
  </div>
<% end %>