config/routes.rb
Rails.application.routes.draw do
  get "/classroom-utilization", to: "classroom_utilization#index"
  get "/days/:date", to: 'events#show_date', as: "show_date"
  get "/weeks/:year/:number", to: 'events#show_week'
  root to: 'events#show_date'
  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :spaces do
    resources :events
  end
  resources :event_types
  resources :recurring_events
  get '/utilizations', to: "utilizations#index"
  resources :recurring_events, only: [:create, :update, :destroy]
  get 'events/check_availability', to: 'events#check_availability'
  get 'events/queue', to: 'events#queue'
  resources :events do
    patch :update_approval
    resources :notes
  end
  get 'settings', to: 'settings#index'
  get 'front-lines', to: 'static#front_lines'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spacey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <link rel='stylesheet' type='text/css' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>
  <%= csrf_meta_tags %>
  <script>
      var favicon = document.createElement("link")
      favicon.setAttribute("rel","icon")
      favicon.setAttribute("href","https://calendar.google.com/googlecalendar/images/favicon_v2013_"+(new Date().getDate())+".ico")
      favicon.setAttribute("type","image/x-icon")
      document.head.appendChild(favicon)
  </script>
</head>
<body>

<h1>
<%= link_to image_tag("astronaut_icon.png"), root_path, class: "home-icon" %>
</h1>
<% if flash[:notice] %>
  <p class="error"><%= flash[:notice].html_safe %></p>
<% end %>
<% if current_user %>
    <%= link_to "Logout #{current_user.name}", logout_path %>
    <br><br>
  <nav>
  <%= link_to '/front-lines', class: 'button' do %>
    <span class='fa fa-cogs'></span> Front Lines Directory
  <% end %>
  <%= link_to utilizations_path, class: 'button' do %>
    <span class='fa fa-line-chart'></span> Utilizations
  <% end %>

  <%= form_tag("/", method: "get") do %>
    <%= text_field_tag(:query, params[:query], {type: "search", placeholder: "Search"}) %>
  <% end %>

  </nav>
<nav>
  <%= link_to new_event_path(day: @dayparams) do %>
    <span class='fa fa-plus'></span> New Event
  <% end %>
  <% if can? :approve, @event %>
    <%= link_to events_queue_path, class:'queue-count' do %>
      Queue
      <% if @queue_count > 0 %>
	      <span><%= @queue_count %></span>
      <% end %>
    <% end %>
    <%= link_to settings_path do%>
      <span class='fa fa-cog'></span> Settings
    <% end %>
  <% end %>
  <%= link_to  show_date_path(Time.now.strftime("%F"),request.query_parameters.except(:start_date, :query)) do %>
    <span class='fa fa-clock-o'></span> Today
  <% end %>
  <a href='#' class='jump-to js-jump-to'>
    Jump to Date
  </a>
</nav>
<br>

<%= yield %>
<% else %>
  Please <%= link_to "log in.", "/auth/google_oauth2" %>
<% end %>

<footer>
<a href='https://github.com/ga-dc/spacey'>
  <svg height="16" width="10" xmlns="http://www.w3.org/2000/svg">
    <path d="M10 5c0-1.11-0.89-2-2-2s-2 0.89-2 2c0 0.73 0.41 1.38 1 1.72v0.3c-0.02 0.52-0.23 0.98-0.63 1.38s-0.86 0.61-1.38 0.63c-0.83 0.02-1.48 0.16-2 0.45V4.72c0.59-0.34 1-0.98 1-1.72 0-1.11-0.89-2-2-2S0 1.89 0 3c0 0.73 0.41 1.38 1 1.72v6.56C0.41 11.63 0 12.27 0 13c0 1.11 0.89 2 2 2s2-0.89 2-2c0-0.53-0.2-1-0.53-1.36 0.09-0.06 0.48-0.41 0.59-0.47 0.25-0.11 0.56-0.17 0.94-0.17 1.05-0.05 1.95-0.45 2.75-1.25s1.2-1.98 1.25-3.02h-0.02c0.61-0.36 1.02-1 1.02-1.73zM2 1.8c0.66 0 1.2 0.55 1.2 1.2s-0.55 1.2-1.2 1.2-1.2-0.55-1.2-1.2 0.55-1.2 1.2-1.2z m0 12.41c-0.66 0-1.2-0.55-1.2-1.2s0.55-1.2 1.2-1.2 1.2 0.55 1.2 1.2-0.55 1.2-1.2 1.2z m6-8c-0.66 0-1.2-0.55-1.2-1.2s0.55-1.2 1.2-1.2 1.2 0.55 1.2 1.2-0.55 1.2-1.2 1.2z" />
  </svg>
  GitHub
</a>
</footer>
</body>
</html>